application:
  notify: "major, minor, patch"
  notification_method: "none" # telegram or slack - must be set
  send_full_changelog: "false"
  log_level: "INFO" # DEBUG or INFO

deployment:
  metadata:
    labels: {}
    annotations: {}

  spec:
    replicas: 1

    template:
      metadata:
        labels: {}

      image:
        image: yuvalpress/version-notifier
        # if tag not set, will default to the chart's appVersion
        #        tag: latest
        imagePullPolicy: IfNotPresent

      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "250"

# not recommended to enable the secret as the values need to be hard coded in the chart
secrets:
  notification:
    enable: disabled
    type: telegram # slack or telegram
    name: version-notifier-notification-secret

    # only if enabled
    values:
      # only if type is slack
      SLACK_TOKEN: dmFsdWU=
      SLACK_CHANNEL: dmFsdWU=
      # only if type is telegram
      TELEGRAM_TOKEN: dmFsdWU=
      TELEGRAM_CHAT_ID: dmFsdWU=

  github:
    enable: disabled
    name: version-notifier-github-secret

    # only if enabled
    values:
      GITHUB_TOKEN: dmFsdWU=



# the repos to scrape
configmap:
  repos:
    - yuvalpress: version-notifier
    - hashicorp: terraform-provider-aws
    - hashicorp: terraform-provider-google
