apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  {{ if .Values.deployment.metadata.labels }}
  {{- range $k, $v := .Values.deployment.metadata.labels }}
    {{ $k }}: {{ $v }}
  {{- end }}
  {{ end }}
  annotations:
  {{ if .Values.deployment.metadata.annotations }}
  {{- range $k, $v := .Values.deployment.metadata.annotations }}
    {{ $k }}: {{ $v }}
  {{- end }}
  {{ end }}
spec:
  replicas: {{ .Values.deployment.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      {{ if .Values.deployment.spec.template.metadata.labels }}
      {{- range $k, $v := .Values.deployment.spec.template.metadata.labels }}
        {{ $k }}: {{ $v }}
      {{- end }}
      {{ end }}
    spec:
      containers:
        - name: version-notifier
          {{ if .Values.deployment.spec.template.image.tag }}
          image: {{ .Values.deployment.spec.template.image.image }}:{{ .Values.deployment.spec.template.image.tag }}
          {{ else }}
          image: {{ .Values.deployment.spec.template.image.image }}:{{ .Chart.AppVersion }}
          {{ end }}
          imagePullPolicy: {{ .Values.deployment.spec.template.image.imagePullPolicy }}
          resources:
            requests:
              memory: {{ .Values.deployment.spec.template.resources.requests.memory }}
              cpu: {{ .Values.deployment.spec.template.resources.requests.cpu }}
            limits:
              memory: {{ .Values.deployment.spec.template.resources.limits.memory }}
              cpu: {{ .Values.deployment.spec.template.resources.limits.cpu }}
          env:
            {{ if .Values.application.notify -}}
            - name: {{ upper "notify" }}
              value: {{ .Values.application.notify }}
            {{ end }}
            - name: {{ upper "notification_method" }}
              {{ if .Values.application.notification_method -}}
              value: {{ .Values.application.notification_method }}
              {{ else -}}
              value: "none"
              {{ end }}
            - name: {{ upper "send_full_changelog" }}
              {{ if .Values.application.send_full_changelog -}}
              value: {{ .Values.application.send_full_changelog }}
              {{ else -}}
              value: "false"
              {{ end }}
            - name: {{ upper "log_level" }}
              {{ if .Values.application.log_level -}}
              value: {{ .Values.application.log_level }}
              {{ else -}}
              value: "INFO"
              {{ end }}
          envFrom:
            - secretRef:
                {{- if .Values.secrets.notification.name }}
                name: {{ .Values.secrets.notification.name }}
                {{- else }}
                name: {{ .Release.Name }}-notification-secret
                {{- end }}
            - secretRef:
                {{- if .Values.secrets.github.name }}
                name: {{ .Values.secrets.github.name }}
                {{- else }}
                name: {{ .Release.Name }}-github-secret
                {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/app/config.yaml"
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-cm
            items:
              - key: "config.yaml"
                path: "config.yaml"