{{ if and .Values.secrets.notification.enable (eq .Values.secrets.notification.type "slack") }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.secrets.notification.name }}
  name: {{ .Values.secrets.notification.name }}
  {{- else }}
  name: {{ .Release.Name }}-notification-secret
  {{- end }}
data:
  SLACK_TOKEN: {{ .Values.secrets.notification.values.SLACK_TOKEN }}
  SLACK_CHANNEL: {{ .Values.secrets.notification.values.SLACK_CHANNEL }}
type: Opaque
{{ else if and .Values.secrets.notification.enable (eq .Values.secrets.notification.type "telegram") }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.secrets.notification.name }}
  name: {{ .Values.secrets.notification.name }}
  {{- else }}
  name: {{ .Release.Name }}-notification-secret
  {{- end }}
data:
  TELEGRAM_TOKEN: {{ .Values.secrets.notification.values.SLACK_TOKEN }}
  TELEGRAM_CHAT_ID: {{ .Values.secrets.notification.values.SLACK_CHANNEL }}
type: Opaque
{{- end }}
---
{{ if .Values.secrets.github.enable }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.secrets.github.name }}
  name: {{ .Values.secrets.github.name }}
  {{- else }}
  name: {{ .Release.Name }}-github-secret
  {{- end }}
data:
  GITHUB_TOKEN: {{ .Values.secrets.github.values.GITHUB_TOKEN }}
type: Opaque
{{- end }}